spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
