server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql:///testdb?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 0
        max-wait: -1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true



