name: lakes
description: Demonstrates building a layout for the "Lakes" app.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

